# Generated by Django 5.2.4 on 2025-08-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_project', '0002_alter_shoes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='type',
            field=models.CharField(choices=[('حريمي', 'حريمي'), ('رجالي', 'رجالي'), ('كوتشي', 'كوتشي'), ('شبشب', 'شبشب')], max_length=80),
        ),
    ]
