# Generated by Django 5.2.4 on 2025-08-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_project', '0003_alter_shoes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=90)),
                ('Price', models.FloatField()),
                ('opreating_system', models.CharField(choices=[('Android', 'Android'), ('Ios', 'Ios'), ('Huewai', 'Huewai')], max_length=90)),
            ],
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
    ]
