# Generated by Django 5.2.4 on 2025-08-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_project', '0004_phones_delete_shoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='Andorid',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phones',
            name='ios',
            field=models.FloatField(null=True),
        ),
    ]
