# Generated by Django 5.2.4 on 2025-08-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_project', '0005_phones_andorid_phones_ios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phones',
            old_name='Price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='phones',
            name='Andorid',
        ),
        migrations.RemoveField(
            model_name='phones',
            name='ios',
        ),
        migrations.RemoveField(
            model_name='phones',
            name='opreating_system',
        ),
        migrations.AddField(
            model_name='phones',
            name='description',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='phones',
            name='img',
            field=models.ImageField(null=True, upload_to='project1/static/img'),
        ),
    ]
