# Generated by Django 5.2.4 on 2025-08-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_project', '0006_rename_price_phones_price_remove_phones_andorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='img',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to=''),
        ),
    ]
