# Generated by Django 5.2.4 on 2025-08-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_project', '0007_alter_phones_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=90)),
                ('password', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
