# Generated by Django 5.2.4 on 2025-08-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_project', '0008_app_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App_users',
        ),
    ]
