# Generated by Django 5.2.4 on 2025-08-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_project', '0009_delete_app_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.IntegerField()),
                ('email', models.EmailField(max_length=90)),
            ],
        ),
        migrations.AlterField(
            model_name='phones',
            name='description',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='phones',
            name='img',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
