# Generated by Django 5.2.4 on 2025-08-23 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_project', '0010_users_alter_phones_description_alter_phones_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
