# Generated by Django 5.2.4 on 2025-08-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_project', '0011_remove_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
