# Generated by Django 5.2.4 on 2025-08-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_project', '0012_alter_users_email_alter_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='password',
        ),
    ]
