# Generated by Django 5.2.4 on 2025-08-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_project', '0013_rename_username_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=90),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=90),
        ),
    ]
