# Generated by Django 5.2.4 on 2025-08-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_project', '0014_alter_users_email_alter_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='instgram_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
            ],
        ),
    ]
